#ifndef TOKEN_H
#define TOKEN_H

struct Token {
    // todo: organize
    enum class Type {
        IDENTIFIER,
        NUMBER,
        STRING,
        EQUAL,
        EQUAL_EQUAL,
        BANG_EQUAL,
        COLON_EQUAL,
        LESS_EQUAL,
        GREATER_EQUAL,
        PLUS_EQUAL,
        MINUS_EQUAL,
        STAR_EQUAL,
        PERCENT_EQUAL,
        SLASH_EQUAL,
        SLASH_SLASH_EQUAL,
        AND_EQUAL,
        BAR_EQUAL,
        CARET_EQUAL,
        LESS_LESS_EQUAL,
        GREATER_GREATER_EQUAL,
        LESS,
        GREATER,
        LEFT_PAREN,
        RIGHT_PAREN,
        LEFT_BRACE,
        RIGHT_BRACE,
        LEFT_BRACKET,
        RIGHT_BRACKET,
        PLUS,
        MINUS,
        STAR,
        SLASH,
        SLASH_SLASH,
        PERCENT,
        AND,
        AND_AND,
        BAR,
        BAR_BAR,
        BANG,
        DOT,
        DOT_DOT,
        DOT_DOT_DOT,
        LESS_LESS,
        GREATER_GREATER,
        CARET,
        TRUE,
        FALSE,
        LOOP,
        IF,
        ELSE,
        IN,
        IS,
        CLASS,
        FUN,
        GET,
        SET,
        NIL,
        END,
        THIS,
        COMMA,
        SEMICOLON,
        DOLLAR
    };

    Type type;
};

#endif //TOKEN_H
